name: Mark tool updates

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Validate and format JSON
        run: node src/lint-json.mjs

      - name: temp
        run: |
          git log -20
          git log -20 --grep="GITBOOK-edgar"

      - name: Mark tool updates
        run: node src/mark-tool-updates.mjs

      - name: Commit tools
        if: steps.changes.outputs.tools == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gitbook/tools
          git commit -m "Mark tool updates"

      - name: Push changes
        if: steps.changes.outputs.all == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: updates
          force: true

      - name: Create Pull Request
        if: steps.changes.outputs.all == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: updates
          commit-message: "Mark tools updated today"
          title: "Mark tool updates"
          body: "This pull request updates timestamps on tool pages"
